export { build } from "./variables/build.js";
export { customInspect } from "./variables/customInspect.js";
export { env } from "./variables/env.js";
export * as errors from "./variables/errors.js";
export { mainModule } from "./variables/mainModule.js";
export { metrics } from "./variables/metrics.js";
export { noColor } from "./variables/noColor.js";
export { permissions } from "./variables/permissions.js";
export { pid } from "./variables/pid.js";
export { ppid } from "./variables/ppid.js";
export { resources } from "./variables/resources.js";
export * from "./variables/std.js";
export { version } from "./variables/version.js";
